name: Vagrant

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: dependencies
      run: sudo apt-get install -y ansible vagrant
    - name: vagrant
      run: vagrant up
