name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: dependencies
      run: apt install -y ansible vagrant
    - name: vagrant
      run: vagrant up
